# Generated by Django 5.2.4 on 2025-07-24 23:07

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_studentadmission_delete_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='campus_tour/')),
                ('is_visible', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Teaching', 'Teaching Staff'), ('Non-Teaching', 'Non-Teaching Staff')], max_length=20)),
                ('position', models.CharField(max_length=100)),
                ('qualifications', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('role_applied', models.CharField(max_length=100)),
                ('application_letter', models.FileField(upload_to='staff_applications/', validators=[main.models.validate_pdf])),
                ('cv', models.FileField(upload_to='staff_applications/', validators=[main.models.validate_pdf])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='academic_results',
            field=models.FileField(upload_to='student_applications/', validators=[main.models.validate_pdf]),
        ),
    ]
